mys SEGMENT PARA 'ODEV'
    ORG 100H
    ASSUME CS:mys, DS:mys, SS:mys
BASLA:  JMP MAIN

primeOddSum DB 15 DUP(0)
nonPrimeOrEvenSum DB 15 DUP(0)
asalDegiskeni DB 1
iki DB 2

ASAL PROC NEAR 
    MOV AX, CS
    MOV DS, AX
    ;CL UZUN KENAR
    MOV BH, CL
    XOR AX, AX
    MOV AL, CL
    DIV iki;BOLUM AL DE
    MOV BL, AL
    ;MOV AL, CL
DONGU:
    CMP BL, 1
    JE ASALDIR
    XOR AX, AX
    MOV AL, CL
    DIV BL
    DEC BL
    CMP AH, 0
    JNE DONGU
ASALDEGIL:
    MOV asalDegiskeni, 0
    JMP SON
ASALDIR:
    MOV asalDegiskeni, 1
SON:
    RET
ASAL ENDP

MAIN PROC NEAR
    ;MOV CX, n
    XOR SI, SI
    XOR DI, DI
    MOV DH, 1; DH DIk KENAR
DIS:
    MOV DL, DH; DL ikinci KENAR, TEKRAR AYNI KOMBİNASYONU HESAPLAMAMASI ICIN DH TAN BASLATTIM
IC:
    MOV AL, DH; ıc dongunun baslangici
    MUL DH
    MOV BX, AX;DH^2
    MOV AL, DL
    MUL DL;DL^2
    ADD BX, AX ; BX = DH^2 + DL^2
    ; c^2=DH^2+BL^2 cyi nasil hesaplarim?
    ;BH+BL > C > BH-BL BU ARALIKTAKİ SAYILARIN KARESINI AL BX İLE KARŞILAŞTIR ESIT MI
    XOR CX, CX
    ADD CH, DH
    ADD CH, DL;CH DİK KENARLARIN TOPLAMI
    MOV CL, DL
    SUB CL, DH;DH KUCUK OLAN YANI DISARDAKI
    ;CL CH ARASINDA FOR OLMASI LAZIM
    ;CL KENARLARIN FARKI CH TOPLAMI
ENIC:
    INC CL
    CMP CL, 50
    JA ICDEVAM
    MOV AL, CL
    MUL CL;CL UZUN KENAR 
    CMP AX, BX
    ;EŞİTSE HİPO ASAL MI VE DL ARTI DH TEK Mİ KONTROLÜ DEĞİLSE CLYİ CHLA KONTROL ET
    JE HIPO

    CMP CL, CH;CH DİK KENARLARIN TOPLAMI
    JB ENIC
    JMP ICDEVAM
DISYOLU:
    JMP DIS;ALTTAKİ YETİŞMİYO
HIPO:
    ;HİPO ASAL MI    
    CALL ASAL
    CMP asalDegiskeni, 0;BOYLE OLUYO MU BAK
    JE ASALYADATEKDEGILSE
;ASALSA TEKMI:
    XOR AX, AX
    MOV AL, CH;CH DİK KENARLARIN TOPLAMI
    DIV iki
    CMP AH, 0
    JE ASALYADATEKDEGILSE

    MOV BX, 0
KARSILASTIRMA:;AYNI KENAR VAR MI KONTROLÜ       
    CMP BX, SI 
    JE EKLE
    CMP CL, primeOddSum[BX]
    INC BX   
    JNE KARSILASTIRMA
    JMP ICDEVAM
EKLE:
    MOV primeOddSum[SI], CL
    INC SI
    JMP ICDEVAM

ASALYADATEKDEGILSE:
    MOV BX, 0
KARSILASTIRMA2:
    CMP BX, DI 
    JAE EKLE2
    CMP CL, nonPrimeOrEvenSum[BX]
    JE ICDEVAM
    INC BX   
    JMP KARSILASTIRMA2
EKLE2:
    MOV nonPrimeOrEvenSum[DI], CL
    INC DI

ICDEVAM:
    CMP DL, 50
    INC DL
    JBE IC; KUÇÜK EŞİT ÇIKMA
    INC DH 
    CMP DH, 50
    JBE DISYOLU
    
    RET
MAIN ENDP
mys ENDS
    END BASLA

